services:
  server:
    container_name: EngineeringChallenge_Server
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app

  client:
    container_name: EngineeringChallenge_Client
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  collaboration:
    container_name: EngineeringChallenge_Collaboration
    build: ./collaboration
    ports:
      - "1234:1234"
    volumes:
      - ./collaboration:/app
      - /app/node_modules
